// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdXlUY-5sq3xj534RDtdseoZ2dxX9z5ts',
    appId: '1:979856082985:web:31ca8385cd9021c93cb438',
    messagingSenderId: '979856082985',
    projectId: 'dance-mate-fc3af',
    authDomain: 'dance-mate-fc3af.firebaseapp.com',
    storageBucket: 'dance-mate-fc3af.firebasestorage.app',
    measurementId: 'G-37WH94XJLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVsEZJZ7ispMe3iiKWDE59kdHLB2NN8W8',
    appId: '1:979856082985:android:bca5f331c1f270dc3cb438',
    messagingSenderId: '979856082985',
    projectId: 'dance-mate-fc3af',
    storageBucket: 'dance-mate-fc3af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuXe4rFCvxR7c4i5w8x926_Nv5QOHsZZ0',
    appId: '1:979856082985:ios:84141a60ec9b6c893cb438',
    messagingSenderId: '979856082985',
    projectId: 'dance-mate-fc3af',
    storageBucket: 'dance-mate-fc3af.firebasestorage.app',
    iosBundleId: 'com.example.dancemateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuXe4rFCvxR7c4i5w8x926_Nv5QOHsZZ0',
    appId: '1:979856082985:ios:84141a60ec9b6c893cb438',
    messagingSenderId: '979856082985',
    projectId: 'dance-mate-fc3af',
    storageBucket: 'dance-mate-fc3af.firebasestorage.app',
    iosBundleId: 'com.example.dancemateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdXlUY-5sq3xj534RDtdseoZ2dxX9z5ts',
    appId: '1:979856082985:web:3a9cb6d45cdf20693cb438',
    messagingSenderId: '979856082985',
    projectId: 'dance-mate-fc3af',
    authDomain: 'dance-mate-fc3af.firebaseapp.com',
    storageBucket: 'dance-mate-fc3af.firebasestorage.app',
    measurementId: 'G-C28W76V460',
  );
}
